import type { Metadata } from "next";

// Import your global CSS file here
import './globals.css';

export const metadata: Metadata = {
  title: "Editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
