export const ANIMATION_TIME_LINE=3000
export const FIXED_ANIMATION_TIME_LINE=12000
export const FRAMES_PER_SECOND = 10;
export const HANDSTAND_ANIMATION_DIRECTION_SPEED = 3000;
export const WALKING_ANIMATION_DIRECTION_SPEED = 3000;
export const WALKING_ANIMATION_SPEED_TIME = 2;

export const WALKING='walking'
export const HANDSTAND='handstand'
export const IMAGE_SIZE=250 * 1024

 